# Generated by Django 3.1 on 2023-01-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CratItem',
            new_name='CartItem',
        ),
    ]
